//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorController.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorController.StringResources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFavorite.
        /// </summary>
        internal static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation added as favorite..
        /// </summary>
        internal static string AnimationAddedAsFavorite {
            get {
                return ResourceManager.GetString("AnimationAddedAsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Wi-fi password..
        /// </summary>
        internal static string EnterWiFiPassword {
            get {
                return ResourceManager.GetString("EnterWiFiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter wifi password..
        /// </summary>
        internal static string EnteWifPassword {
            get {
                return ResourceManager.GetString("EnteWifPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please try again.
        /// </summary>
        internal static string IncorrectPasswordPleaseTryAgain {
            get {
                return ResourceManager.GetString("IncorrectPasswordPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of this app available. Would you like to update now?.
        /// </summary>
        internal static string NewVersionMessage {
            get {
                return ResourceManager.GetString("NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter device name.
        /// </summary>
        internal static string PleaseEnterDeviceName {
            get {
                return ResourceManager.GetString("PleaseEnterDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn ON your Bluetooth..
        /// </summary>
        internal static string PleaseTurnONBT {
            get {
                return ResourceManager.GetString("PleaseTurnONBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable location permission from app settings to scan devices..
        /// </summary>
        internal static string PleaseTurnONGPS {
            get {
                return ResourceManager.GetString("PleaseTurnONGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWR.
        /// </summary>
        internal static string POWR {
            get {
                return ResourceManager.GetString("POWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT.
        /// </summary>
        internal static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReloadAnimation.
        /// </summary>
        internal static string ReloadAnimation {
            get {
                return ResourceManager.GetString("ReloadAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendDFUQCommand.
        /// </summary>
        internal static string SendDFUQCommand {
            get {
                return ResourceManager.GetString("SendDFUQCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowConnect.
        /// </summary>
        internal static string ShowConnect {
            get {
                return ResourceManager.GetString("ShowConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowConnecting.
        /// </summary>
        internal static string ShowConnecting {
            get {
                return ResourceManager.GetString("ShowConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowDisconnect.
        /// </summary>
        internal static string ShowDisconnect {
            get {
                return ResourceManager.GetString("ShowDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowSearching.
        /// </summary>
        internal static string ShowSearching {
            get {
                return ResourceManager.GetString("ShowSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to update your controller&apos;s firmware to access this animation..
        /// </summary>
        internal static string UpdateControllerFirmwareToPlayAnimation {
            get {
                return ResourceManager.GetString("UpdateControllerFirmwareToPlayAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We noticed &quot;5G&quot; is in your Wi-Fi network name. The LightMode controller is not compatible with 5G. If you continue with a 5G network, the update will fail..
        /// </summary>
        internal static string WeNoticed5G {
            get {
                return ResourceManager.GetString("WeNoticed5G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
